apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pacman
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: quay.io/jpacker/nodejs-pacman-app:latest
          ports:
            - containerPort: 8080
