apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pacman
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: quay.io/jpacker/nodejs-pacman-app:latest
          ports:
            - containerPort: 8080
